version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:14.17

jobs:
  build:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule update --init --recursive

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint
      - run: yarn build

  deploy:
    executor: node
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - '07:51:01:ba:d0:49:5d:57:73:2a:2d:c7:aa:7c:cc:3b'
      - run:
          name: Prepare SSH
          command: |
            ssh-keyscan -H 3.142.187.92 >> ~/.ssh/known_hosts
      - run:
          name: Deploy over SSH
          command: |
            ssh -L  31231:54.91.178.219:22 -N -f -o "StrictHostKeyChecking no" ubuntu@3.142.187.92 -p 31231
            ssh -o "StrictHostKeyChecking no" ubuntu@$PRIVATE_IP "sh /home/ubuntu/pastel-explorer-backend/restart-app.sh"

  deploy-staging:
    executor: node
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'af:60:72:69:24:30:f6:31:96:e7:3e:2a:42:21:84:bd'
      - run:
          name: Deploy Staging over SSH
          command: ssh -o "StrictHostKeyChecking no" ubuntu@$STAGING_SERVER_IP "sh /home/ubuntu/backend-explorer/restart-app.sh"

workflows:
  version: 2
  main:
    jobs:
      - build:
          name: build-pr
          context: explorer-backend-staging
          filters:
            branches:
              only:
                - staging
      - build:
          name: build-production
          context: explorer-backend-production
          filters:
            branches:
              only:
                - staging

      - deploy:
          name: deploy-production
          context: explorer-backend-production
          requires:
            - build-production
          filters:
            branches:
              only:
                - staging
      - deploy-staging:
          name: deploy-staging
          context: explorer-backend-staging
          requires:
            - build-pr
          filters:
            branches:
              only:
                - staging
